### ISSUE TITLE
ShairPort doesn't seem to be working

### ISSUE THREAD

**Issue by enomam** [devdems/logitechmediaserver#4]
I've been unable to use any of my squeezebox clients as ShairPort receivers.
I get a lot of the following messages:

```
Plugins::ShairTunes2W::Plugin::publishPlayer (434) start avahi-publish-service "pisqueezelite"
Failed to create client object: An unexpected D-Bus error occured
```

My compose file looks like this:
```
version: '3'
services:
  lms:
    container_name: lms
    image: snoopy86/logitechmediaserver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /<somewhere>:/config:rw
      - /<somewhere else>:/music:ro
      - /var/run/dbus:/var/run/dbus:rw
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    restart: always
```

Is there a port I'm missing?
